//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_3_ASP.NET_MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_booking
    {
        public int b_id { get; set; }
        public System.DateTime b_bdate { get; set; }
        public System.DateTime b_rdate { get; set; }
        public decimal b_total { get; set; }
        public int b_status { get; set; }
        public int b_customer { get; set; }
        public int b_vehicle { get; set; }
    
        public virtual tb_vehicle tb_vehicle { get; set; }
        public virtual tb_user tb_user { get; set; }
    }
}
