//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_3_ASP.NET_MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_state
    {
        public string state { get; set; }
    }
}
